import Head from 'next/head';
import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles({
  container: {},
  main: {},
  footer: {},
});

const Layout = ({ children }) => {
  const styles = useStyles();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>dsds</p>
        {children}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Layout;
